export type AgeFilter = '18-29' | '30-39' | '40-49' | '50-65+';
export type SexFilter = 'FEMALE' | 'MALE';

export interface GalleryCase {
    id: number;
    image?: string;          // legacy: single combined before/after image
    beforeImage?: string;    // Drive: separate before photo
    afterImage?: string;     // Drive: separate after photo
    age: AgeFilter;
    sex: SexFilter;
    procedure: string;
    objectPosition?: string; // CSS objectPosition for custom framing
    scale?: number;          // CSS scale for zoom adjustment
}

export interface ProcedureConfig {
    title: string;
    subtitle: string;
    heroImage: string;
    treatmentHref: string;
    cases: GalleryCase[];
}

export const procedureConfig: Record<string, ProcedureConfig> = {
    'blepharoplasty': {
        title: 'BLEPHAROPLASTY',
        subtitle: 'BEFORE & AFTER PHOTOS',
        heroImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/actual-patient-photos.webp',
        treatmentHref: '/treatments/eyelid-surgery',
        cases: [
            { id: 1, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/1before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/1after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 2, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/2before-m-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/2after-m-40-49.webp', age: '40-49', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 3, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/3before-m-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/3after-m-50-59.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 4, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/4before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/4after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 5, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/5before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/5after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 6, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/6before-f-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/6after-f-50-59.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 7, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/7before-f-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/7after-f-50-59.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 8, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/8before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/8after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 9, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/9before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/9after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 10, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/10before-f-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/10after-f-50-59.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 11, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/11before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/11after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 12, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/12before-m-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/12after-m-50-59.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 13, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/13before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/13after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 14, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/14before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/14after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 15, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/15before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/15after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 16, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/16before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/16after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 17, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/17before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/17after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 18, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/18before-f-18-19.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/18after-f-18-19.webp', age: '18-29', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 19, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/19before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/19after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 20, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/20before-m-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/20after-m-40-49.webp', age: '40-49', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 21, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/21before-f-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/21after-f-50-59.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 22, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/22before-m-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/22after-m-50-59.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 23, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/23before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/23after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 24, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/24before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/24after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 25, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/25before-m-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/25after-m-50-59.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 28, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/28before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/28after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 29, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/29before-m-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/29after-m-40-49.webp', age: '40-49', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 30, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/30before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/30after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 31, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/31before-f-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/31after-f-50-59.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 32, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/32before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/32after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 33, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/33before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/33after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 34, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/34before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/34after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 35, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/35before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/35after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 36, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/36before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/36after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 37, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/37before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/37after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 38, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/38before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/38after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 39, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/39before-m-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/39after-m-50-59.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 40, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/40before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/40after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 41, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/41before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/41after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 42, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/42before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/42after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 43, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/43before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/43after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 44, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/44before-m-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/44after-m-40-49.webp', age: '40-49', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 45, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/45before-m-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/45after-m-50-59.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 46, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/46before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/46after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 47, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/47before-f-30-39.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/47after-f-30-39.webp', age: '30-39', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 48, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/48before-f-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/48after-f-50-59.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 49, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/49before-f-30-39.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/49after-f-30-39.webp', age: '30-39', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 50, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/50before-f-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/50after-f-50-59.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 51, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/51before-f-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/51after-f-50-59.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 52, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/52before-m-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/52after-m-40-49.webp', age: '40-49', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 53, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/53before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/53after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 54, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/54before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/54after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 55, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/55before-m-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/55after-m-40-49.webp', age: '40-49', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 56, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/56before-m-18-29.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/56after-m-18-29.webp', age: '18-29', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 57, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/57before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/57after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 58, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/58before-m-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/58after-m-50-59.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 59, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/59before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/59after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 60, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/60before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/60after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 61, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/61before-f-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/61after-f-50-59.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 62, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/62before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/62after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 63, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/63before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/63after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 64, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/64before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/64after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 65, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/65before-f-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/65after-f-50-59.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 66, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/66before-f-30-39.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/66after-f-30-39.webp', age: '30-39', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 69, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/69before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/69after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 70, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/70before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/70after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 71, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/71before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/71after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 72, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/72before-m-30-39.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/72after-m-30-39.webp', age: '30-39', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 73, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/73before-m-30-39.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/73after-m-30-39.webp', age: '30-39', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 74, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/74before-f-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/74after-f-50-59.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 75, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/75before-f-18-29.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/75after-f-18-29.webp', age: '18-29', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 76, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/76before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/76after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 77, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/77before-f-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/77after-f-50-59.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 78, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/78before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/78after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 79, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/79before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/79after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 80, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/80before-f-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/80after-f-40-49.webp', age: '40-49', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 81, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/81before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/81after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 82, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/82before-m-40-49.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/82after-m-40-49.webp', age: '40-49', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 83, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/83before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/83after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 84, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/84before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/84after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 85, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/85before-m-50-59.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/85after-m-50-59.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 86, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/86before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/86after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 87, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/87before-m-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/87after-m-60.webp', age: '50-65+', sex: 'MALE', procedure: 'BLEPHAROPLASTY' },
            { id: 88, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/88before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/88after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 89, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/89before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/89after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 90, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/90before-f-60.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/90after-f-60.webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
            { id: 91, beforeImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/91before-f-30-39.webp', afterImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drive-gallery/blepharoplasty/91after-f-30-39.webp', age: '30-39', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY' },
        
        ],
    },
    'ptosis-repair': {
        title: 'PTOSIS REPAIR',
        subtitle: 'BEFORE & AFTER PHOTOS',
        heroImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/actual-patient-photos.webp',
        treatmentHref: '/treatments/medical-eye-care',
        cases: [
            { id: 1, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (1).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 2, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (2).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 3, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (3).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 4, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (4).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 5, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (5).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 6, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (6).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 7, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (7).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 8, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (8).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 9, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (9).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 10, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (10).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 11, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (11).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 12, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (12).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 13, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (13).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 14, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (14).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 15, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (15).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 16, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (16).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 17, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (17).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 18, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (18).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 19, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (19).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 20, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (20).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 21, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (21).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 22, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (22).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 23, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (23).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 24, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (24).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 25, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (25).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 26, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (26).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 27, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (27).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 28, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (28).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 29, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (29).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 30, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (30).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 31, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (31).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 32, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (32).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 33, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (33).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 34, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (34).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 35, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (35).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 36, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (36).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 37, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (37).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 38, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (38).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 39, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (39).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 40, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (40).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 41, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (41).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 42, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (42).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 43, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (43).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 44, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (44).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 45, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (45).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 46, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (46).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 47, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (47).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 48, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (48).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 49, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (49).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 50, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (50).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 51, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (51).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 52, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (52).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 53, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (53).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 54, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (54).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 55, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (55).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 56, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (56).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 57, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (57).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 58, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (58).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 59, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (59).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 60, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (60).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 61, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (61).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 62, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (62).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 63, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (63).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 64, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (64).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 65, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (65).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 66, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (66).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 67, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (67).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 68, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (68).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 69, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (69).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 70, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (70).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 71, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (71).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 72, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (72).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' },
            { id: 73, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/ptosis-repair/Ptosis Repair (73).webp', age: '50-65+', sex: 'FEMALE', procedure: 'PTOSIS REPAIR' }
        ],
    },
    'tumor-removal': {
        title: 'TUMOR REMOVAL AND RECONSTRUCTION',
        subtitle: 'BEFORE & AFTER PHOTOS',
        heroImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/actual-patient-photos.webp',
        treatmentHref: '/treatments/medical-eye-care',
        cases: [
            { id: 1, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (1).webp', age: '50-65+', sex: 'MALE', procedure: 'TUMOR REMOVAL' },
            { id: 2, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (2).webp', age: '50-65+', sex: 'MALE', procedure: 'TUMOR REMOVAL' },
            { id: 3, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (3).webp', age: '50-65+', sex: 'MALE', procedure: 'TUMOR REMOVAL' },
            { id: 4, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (4).webp', age: '50-65+', sex: 'MALE', procedure: 'TUMOR REMOVAL' },
            { id: 5, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (5).webp', age: '40-49', sex: 'MALE', procedure: 'TUMOR REMOVAL' },
            { id: 6, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (6).webp', age: '50-65+', sex: 'MALE', procedure: 'TUMOR REMOVAL' },
            { id: 7, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (7).webp', age: '40-49', sex: 'FEMALE', procedure: 'TUMOR REMOVAL' },
            { id: 8, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (8).webp', age: '50-65+', sex: 'FEMALE', procedure: 'TUMOR REMOVAL' },
            { id: 9, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (9).webp', age: '50-65+', sex: 'FEMALE', procedure: 'TUMOR REMOVAL' },
            { id: 10, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (10).webp', age: '50-65+', sex: 'FEMALE', procedure: 'TUMOR REMOVAL' },
            { id: 11, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (11).webp', age: '18-29', sex: 'MALE', procedure: 'TUMOR REMOVAL' },
            { id: 12, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (12).webp', age: '50-65+', sex: 'MALE', procedure: 'TUMOR REMOVAL' },
            { id: 13, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (13).webp', age: '40-49', sex: 'FEMALE', procedure: 'TUMOR REMOVAL' },
            { id: 14, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (14).webp', age: '50-65+', sex: 'MALE', procedure: 'TUMOR REMOVAL' },
            { id: 15, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (15).webp', age: '50-65+', sex: 'MALE', procedure: 'TUMOR REMOVAL' },
            { id: 16, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/tumor-removal/Eye Tumor Removal (16).webp', age: '50-65+', sex: 'MALE', procedure: 'TUMOR REMOVAL' },
        ],
    },
    '5d-eyebag-removal': {
        title: '5D EYEBAG REMOVAL',
        subtitle: 'BEFORE & AFTER PHOTOS',
        heroImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/actual-patient-photos.webp',
        treatmentHref: '/treatments/non-surgical',
        cases: [
            { id: 1, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/new/5D%20Eyelift%20(1).webp', age: '40-49', sex: 'FEMALE', procedure: '5D EYELIFT' },
            { id: 2, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/new/5D%20Eyelift%20(2).webp', age: '40-49', sex: 'FEMALE', procedure: '5D EYELIFT' },
        ],
    },
    '5d-face-lift': {
        title: '5D FACE LIFT',
        subtitle: 'BEFORE & AFTER PHOTOS',
        heroImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/actual-patient-photos.webp',
        treatmentHref: '/treatments/non-surgical',
        cases: [
            { id: 1, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/3d-Facelift/5D%20Face%20Lift%20(1).webp', age: '40-49', sex: 'FEMALE', procedure: '5D FACE LIFT' },
            { id: 2, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/3d-Facelift/5D%20Face%20Lift%20(2).webp', age: '40-49', sex: 'FEMALE', procedure: '5D FACE LIFT' },
        ],
    },
    'laser-skin-resurfacing': {
        title: 'LASER SKIN RESURFACING',
        subtitle: 'BEFORE & AFTER PHOTOS',
        heroImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/actual-patient-photos.webp',
        treatmentHref: '/treatments/non-surgical',
        cases: [
            { id: 1, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/laser-skin-resurfacing/Erbium Laser (1).webp', age: '50-65+', sex: 'FEMALE', procedure: 'LASER SKIN RESURFACING' },
            { id: 2, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/laser-skin-resurfacing/Erbium Laser (2).webp', age: '50-65+', sex: 'FEMALE', procedure: 'LASER SKIN RESURFACING' },
            { id: 3, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/laser-skin-resurfacing/Erbium Laser (3).webp', age: '50-65+', sex: 'FEMALE', procedure: 'LASER SKIN RESURFACING' },
            { id: 4, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/laser-skin-resurfacing/Erbium Laser (4).webp', age: '50-65+', sex: 'FEMALE', procedure: 'LASER SKIN RESURFACING' },
            { id: 5, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/laser-skin-resurfacing/Erbium Laser (5).webp', age: '50-65+', sex: 'FEMALE', procedure: 'LASER SKIN RESURFACING' },
            { id: 6, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/laser-skin-resurfacing/Erbium Laser (6).webp', age: '50-65+', sex: 'FEMALE', procedure: 'LASER SKIN RESURFACING' },
            { id: 7, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/laser-skin-resurfacing/Erbium Laser (7).webp', age: '50-65+', sex: 'FEMALE', procedure: 'LASER SKIN RESURFACING' },
            { id: 8, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/laser-skin-resurfacing/Erbium Laser (8).webp', age: '50-65+', sex: 'FEMALE', procedure: 'LASER SKIN RESURFACING' },
            { id: 9, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/laser-skin-resurfacing/Erbium Laser (9).webp', age: '50-65+', sex: 'FEMALE', procedure: 'LASER SKIN RESURFACING' },
            { id: 10, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/laser-skin-resurfacing/Erbium Laser (10).webp', age: '50-65+', sex: 'FEMALE', procedure: 'LASER SKIN RESURFACING' },
            { id: 11, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/laser-skin-resurfacing/Erbium Laser (11).webp', age: '50-65+', sex: 'FEMALE', procedure: 'LASER SKIN RESURFACING' },
            { id: 12, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/laser-skin-resurfacing/Erbium Laser (12).webp', age: '50-65+', sex: 'FEMALE', procedure: 'LASER SKIN RESURFACING' },
        ],
    },
    'pdo-thread-lift': {
        title: 'PDO THREAD LIFT FOR SKIN TIGHTENING',
        subtitle: 'BEFORE & AFTER PHOTOS',
        heroImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/actual-patient-photos.webp',
        treatmentHref: '/treatments/non-surgical/pdo-thread-lift',
        cases: [
            { id: 1, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/pdo-thread-lift/1-pdo.webp', age: '50-65+', sex: 'FEMALE', procedure: 'PDO THREAD LIFT' },
            { id: 2, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/pdo-thread-lift/2-pdo.webp', age: '50-65+', sex: 'FEMALE', procedure: 'PDO THREAD LIFT' },
            { id: 3, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/pdo-thread-lift/3-pdo.webp', age: '50-65+', sex: 'FEMALE', procedure: 'PDO THREAD LIFT' },
            { id: 4, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/pdo-thread-lift/4-pdo.webp', age: '50-65+', sex: 'FEMALE', procedure: 'PDO THREAD LIFT' },
            { id: 5, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/pdo-thread-lift/5-pdo.webp', age: '50-65+', sex: 'FEMALE', procedure: 'PDO THREAD LIFT' },
            { id: 6, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/pdo-thread-lift/6-pdo.webp', age: '50-65+', sex: 'FEMALE', procedure: 'PDO THREAD LIFT' },
            { id: 7, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/pdo-thread-lift/7-pdo.webp', age: '50-65+', sex: 'FEMALE', procedure: 'PDO THREAD LIFT' },
        ],
    },
    'drop-n-lift': {
        title: "DROP N' LIFT & UPNEEQ",
        subtitle: 'BEFORE & AFTER PHOTOS',
        heroImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/actual-patient-photos.webp',
        treatmentHref: '/treatments/non-surgical',
        cases: [
            { id: 1, image: "https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drop-in-lift/Drop%20n'%20Lift%20(1).webp", age: '50-65+', sex: 'FEMALE', procedure: 'DROP N\' LIFT' },
            { id: 2, image: "https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drop-in-lift/Drop%20n'%20Lift%20(2).webp", age: '50-65+', sex: 'FEMALE', procedure: 'DROP N\' LIFT' },
            { id: 3, image: "https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drop-in-lift/Drop%20n'%20Lift%20(3).webp", age: '50-65+', sex: 'FEMALE', procedure: 'DROP N\' LIFT' },
            { id: 4, image: "https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drop-in-lift/Drop%20n'%20Lift%20(4).webp", age: '50-65+', sex: 'FEMALE', procedure: 'DROP N\' LIFT' },
            { id: 5, image: "https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/gallery/drop-in-lift/Drop%20n'%20Lift%20(5).webp", age: '50-65+', sex: 'FEMALE', procedure: 'DROP N\' LIFT' },
        ],
    },
    'botox': {
        title: 'NEUROMODULATORS & DERMAL FILLERS',
        subtitle: 'BEFORE & AFTER PHOTOS',
        heroImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/actual-patient-photos.webp',
        treatmentHref: '/treatments/injectables',
        cases: [
            { id: 1, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (1).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 2, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (2).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 3, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (3).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 4, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (4).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 5, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (5).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 6, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (6).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 7, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (7).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 8, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (8).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 9, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (9).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 10, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (10).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 11, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (11).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 12, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (12).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 13, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (13).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 14, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (14).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 15, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (15).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 16, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (16).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 17, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (17).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 18, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (18).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 19, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (19).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 20, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/botox/Botox (20).webp', age: '50-65+', sex: 'FEMALE', procedure: 'NEUROMODULATORS' },
            { id: 21, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/restylane/Restylane Lip Filler (1).webp', age: '50-65+', sex: 'FEMALE', procedure: 'DERMAL FILLERS' },
            { id: 22, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/restylane/Restylane Lip Filler (2).webp', age: '50-65+', sex: 'FEMALE', procedure: 'DERMAL FILLERS' },
            { id: 23, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/restylane/Restylane Lip Filler (4).webp', age: '50-65+', sex: 'FEMALE', procedure: 'DERMAL FILLERS' },
            { id: 24, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/restylane/Restylane Lip Filler (5).webp', age: '50-65+', sex: 'FEMALE', procedure: 'DERMAL FILLERS' },
            { id: 25, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/restylane/Restylane Lip Filler (6).webp', age: '50-65+', sex: 'FEMALE', procedure: 'DERMAL FILLERS' },
            { id: 26, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/restylane/Restylane Lip Filler (7).webp', age: '50-65+', sex: 'FEMALE', procedure: 'DERMAL FILLERS' },
            { id: 27, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/restylane/Restylane Lip Filler (8).webp', age: '50-65+', sex: 'FEMALE', procedure: 'DERMAL FILLERS' },
            { id: 28, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/restylane/Restylane Lip Filler (9).webp', age: '50-65+', sex: 'FEMALE', procedure: 'DERMAL FILLERS' },
            { id: 29, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/restylane/Restylane Lip Filler (10).webp', age: '50-65+', sex: 'FEMALE', procedure: 'DERMAL FILLERS' },
        ],
    },
    'bleph-and-ptosis': {
        title: 'BLEPHAROPLASTY & PTOSIS REPAIR',
        subtitle: 'BEFORE & AFTER PHOTOS',
        heroImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/actual-patient-photos.webp',
        treatmentHref: '/treatments/eyelid-surgery',
        cases: [
            { id: 1, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/bleph-and-ptosis/Blepharoplasty + Ptosis (1).webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY & PTOSIS REPAIR' },
            { id: 2, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/bleph-and-ptosis/Blepharoplasty + Ptosis (2).webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY & PTOSIS REPAIR' },
            { id: 3, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/bleph-and-ptosis/Blepharoplasty + Ptosis (3).webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY & PTOSIS REPAIR' },
            { id: 4, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/bleph-and-ptosis/Blepharoplasty + Ptosis (4).webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY & PTOSIS REPAIR' },
            { id: 5, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/bleph-and-ptosis/Blepharoplasty + Ptosis (5).webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY & PTOSIS REPAIR' },
            { id: 6, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/bleph-and-ptosis/Blepharoplasty + Ptosis (6).webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY & PTOSIS REPAIR' },
            { id: 7, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/bleph-and-ptosis/Blepharoplasty + Ptosis (7).webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY & PTOSIS REPAIR' },
            { id: 8, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/bleph-and-ptosis/Blepharoplasty + Ptosis (8).webp', age: '50-65+', sex: 'FEMALE', procedure: 'BLEPHAROPLASTY & PTOSIS REPAIR' },
        ],
    },
    'ectropion-entropion': {
        title: 'ECTROPION & ENTROPION REPAIR',
        subtitle: 'BEFORE & AFTER PHOTOS',
        heroImage: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/actual-patient-photos.webp',
        treatmentHref: '/treatments/medical-eye-care/ectropion-entropion-repair',
        cases: [
            { id: 1, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/1-ectropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ECTROPION' },
            { id: 2, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/2-ectropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ECTROPION' },
            { id: 3, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/3-ectropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ECTROPION' },
            { id: 4, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/4-ectropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ECTROPION' },
            { id: 5, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/5-ectropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ECTROPION' },
            { id: 6, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/6-ectropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ECTROPION' },
            { id: 7, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/7-ectropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ECTROPION' },
            { id: 8, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/8-ectropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ECTROPION' },
            { id: 9, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/9-ectropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ECTROPION' },
            { id: 10, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/10-ectropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ECTROPION' },
            { id: 11, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/11-ectropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ECTROPION' },
            { id: 12, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/12-ectropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ECTROPION' },
            { id: 13, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/13-ectropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ECTROPION' },
            { id: 14, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/14-entropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ENTROPION' },
            { id: 15, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/15-entropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ENTROPION' },
            { id: 16, image: 'https://zpcxjvbgxvfrcnlixnrb.supabase.co/storage/v1/object/public/site-assets/gallery/drive-gallery/ectropion-entropion/16-entropion.webp', age: '50-65+', sex: 'FEMALE', procedure: 'ENTROPION' },
        ],
    },
};
